language: node_js
node_js:
  - "4"
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - 'npm prune'
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && npm run deploy || false'
sudo: required
env:
  global:
    - GH_REF: github.com/rain2o/champions.git
branches:
  only:
    - master
